# Generated by Django 5.0.1 on 2024-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('detail', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('cat', models.IntegerField(choices=[(1, 'Pizza'), (2, 'Cake'), (3, 'Chicken'), (4, 'Snadwich'), (5, 'Burger')], verbose_name='Category')),
                ('is_active', models.BooleanField(default=1, verbose_name='Status')),
            ],
        ),
    ]
