# Generated by Django 5.0.1 on 2024-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='f_type',
            field=models.IntegerField(choices=[(1, 'VEG'), (2, 'NON-VEG')], default=2, verbose_name='Food Type'),
            preserve_default=False,
        ),
    ]
