# Generated by Django 5.0.1 on 2024-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_product_f_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='productapp/image'),
        ),
    ]
